# Generated by Django 3.1 on 2020-08-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('car_make', 'car_model')},
            },
        ),
    ]
